#ifndef CONSTANTS_H
#define CONSTANTS_H
#define WIFI_SSID "YOUR_SSID"
#define WIFI_PASS "YOUR_PASSWORD"
#define MQTT_BROKER_HOST "YOUR_MQTT_BROKER_HOST"
#define CLIENT_ID "YOUR_CLIENT_ID"
#define SUBSCRIBE_TOPIC "YOUR_SUBSCRIBE_TOPIC"

const int MQTT_BROKER_PORT = 1883;
const int TRANSMISSION_SPEED = 115200;
const int LEDS_COUNT = 6;
const int SUBSCRIPTIONS_MQTT = 6;
const int ledPins[LEDS_COUNT] = {15, 2, 5, 18, 21, 23};
const int STAND_BY_DELAY = 200;
#endif