#ifndef CONSTANTS_H
#define CONSTANTS_H
#define WIFI_SSID "YOUR_SSID"
#define WIFI_PASS "YOUR_PASSWORD"
#define MQTT_BROKER_HOST "YOUR_MQTT_BROKER_HOST"
#define CLIENT_ID "YOUR_CLIENT_ID"
#define PUBLISH_TOPIC "YOUR_PUBLISH_TOPIC"

const int MQTT_BROKER_PORT = 1883;
const byte TRIGGER_PIN = 5;
const byte ECHO_PIN = 18;
const int TRANSMISSION_SPEED = 115200;
const byte SAMPLE_SIZE = 10;
const int LIMIT_DELAY = 1000;
const int STAND_BY_DELAY = 200;

#endif